### ISSUE TITLE
Error in project load due to currupted project filr

### ISSUE THREAD

**Issue by vipinbeni** [hsluoyz/VisualADS#1]
I m trying to run this project but it can not load in visual studio 2008 and 2010 pls help me .

**Comment by hsluoyz** [comment]
Plz run this project in VC6, unless you can handle the compatibility thing between VC6 and VC2008.

**Comment by vipinbeni** [comment]
could you tell me how can i open it in vc 6 i have install vc6 right now but when  i open dsw file no message and nothing is open...

**Comment by hsluoyz** [comment]
VC6 SP6  (Service Pack 6) should be installed before you open the DSW file

**Comment by vipinbeni** [comment]
.
![1233](https://f.cloud.github.com/assets/5228833/1992867/c29f30f0-84cc-11e3-8684-38104e5b0cc8.png)
![2](https://f.cloud.github.com/assets/5228833/1992872/fd71d11a-84cc-11e3-85c2-969931321f47.png)

i already install vc 60 but nothing shown in left side is there is any problem in dsw or dsp file . or you could tell me how can i build it on vc2008 .

**Comment by hsluoyz** [comment]
Please upgrade it to a modern Visual Studio, and report any errors to me.

**Comment by hsluoyz** [comment]
I suppose this issue has been fixed.
